direction: right
classes: {
  c4_person: {
    style.fill: "#f5f1ff"
    style.stroke: "#6f4bb2"
    style.font-color: "#211436"
  }
}
user: {
  label: "User"
  shape: c4-person
  class: ["c4_person"]
}
app: "My App"
user -> app: "Uses\n[HTTPS]"
