site_name: c4-diagrams
repo_url: https://github.com/sidorov-as/c4-diagrams
site_url: https://sidorov-as.github.io/c4-diagrams
site_description: A Python DSL for generating C4 diagrams
site_author: Alexey Sidorov
edit_uri: edit/main/docs/
repo_name: sidorov-as/c4-diagrams
copyright: Maintained by <a href="https://github.com/sidorov-as">sidorov-as</a>.

nav:
  - Home:
    - Home: index.md
    - Introduction: introduction.md
    - Contributing: contributing.md
    - Changelog: changelog.md
  - Diagrams:
      - System context: diagrams/system-context.md
      - Containers: diagrams/containers.md
      - Components: diagrams/components.md
      - Supporting diagrams: diagrams/supporting.md
  - Rendering backends:
      - PlantUML: renderers/plantuml.md

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: ["c4"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  language: en
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  logo: assets/c4-diagrams.png
  favicon: assets/favicon.ico

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sidorov-as/c4-diagrams
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/c4-diagrams

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
