[tox]
requires =
    tox-uv>=1.29
skipsdist = true
envlist = py310, py311, py312, py313, py314

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
runner = uv-venv-lock-runner
passenv = PYTHON_VERSION
allowlist_externals = uv
commands =
    {envpython} --version
    {envpython} -m mypy
    {envpython} -m pytest --doctest-modules tests --cov --cov-config=pyproject.toml --cov-report=xml
