from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from c4.diagrams.core import (
    Diagram,
    DiagramType,
    Element,
    ElementExtensions,
    ElementWithTechnology,
)
from c4.utils import MISSING, REQUIRED, Maybe, Required

if TYPE_CHECKING:  # pragma: no cover
    from c4.contrib.d2.extensions import (
        ElementExtensions as D2ElementExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        ComponentExtensions as PlantUMLComponentExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        ComponentStorageExtensions as PlantUMLComponentStorageExtensions,
    )

AllowedDiagramTypes = tuple[DiagramType, ...] | None


ALLOWED_DIAGRAM_TYPES: tuple[DiagramType, ...] = (
    DiagramType.COMPONENT_DIAGRAM,
    DiagramType.DYNAMIC_DIAGRAM,
    DiagramType.DEPLOYMENT_DIAGRAM,
)


class ComponentDiagram(Diagram):
    """
    Represents a [C4 Component diagram](https://c4model.com/diagrams/component).
    """

    type: ClassVar[DiagramType] = DiagramType.COMPONENT_DIAGRAM


class Component(Element):
    """
    Represents a software component within a container.

    A component is a logical unit (such as a class, module, or handler)
    that performs a specific function within a container. Includes metadata
    like technology, visual style, and links.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        technology: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLComponentExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a component element.

        Args:
            label: Display name for the component. Required.
            description: Optional description of the component's
                behavior or role.
            technology: Optional technology used to implement the component.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the component. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            alias=alias,
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
        )

        self.technology = technology


class ComponentDb(ElementWithTechnology):
    """
    Represents a component modeled as a database.

    Used to depict data storage components in a component diagram.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        technology: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLComponentStorageExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a database-like component element.

        Args:
            label: Display name for the component database. Required.
            description: Optional description text.
            technology: Optional technology used by the component.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the component database. If not
                provided, it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            technology=technology,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class ComponentQueue(ElementWithTechnology):
    """
    Represents a component modeled as a message queue.

    Useful for showing message-based or asynchronous communication paths.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        technology: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLComponentStorageExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a queue-like component element.

        Args:
            label: Display name for the component queue. Required.
            description: Optional description text.
            technology: Optional technology used by the component.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the component queue. If not provided,
                it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            technology=technology,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class ComponentExt(Component):
    """
    Represents an external component outside the container boundary.

    Commonly used to show third-party libraries or external system components.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES


class ComponentDbExt(ComponentDb):
    """
    Represents an external database component.

    Used for visualizing data stores not maintained by the system.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES


class ComponentQueueExt(ComponentQueue):
    """
    Represents an external message queue or broker.

    Used to show external infrastructure for asynchronous communication.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES


__all__ = (
    "Component",
    "ComponentDb",
    "ComponentDbExt",
    "ComponentDiagram",
    "ComponentExt",
    "ComponentQueue",
    "ComponentQueueExt",
)
