from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from c4.diagrams.core import (
    Boundary,
    Diagram,
    DiagramType,
    Element,
    ElementExtensions,
    ElementWithTechnology,
)
from c4.utils import MISSING, REQUIRED, Maybe, Required

if TYPE_CHECKING:  # pragma: no cover
    from c4.contrib.d2.extensions import (
        BoundaryExtensions as D2BoundaryExtensions,
    )
    from c4.contrib.d2.extensions import (
        ElementExtensions as D2ElementExtensions,
    )
    from c4.contrib.mermaid.extensions import (
        BoundaryExtensions as MermaidBoundaryExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        BoundaryExtensions as PlantUMLBoundaryExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        ContainerExtensions as PlantUMLContainerExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        ContainerStorageExtensions as PlantUMLContainerStorageExtensions,
    )

AllowedDiagramTypes = tuple[DiagramType, ...] | None


ALLOWED_DIAGRAM_TYPES: tuple[DiagramType, ...] = (
    DiagramType.CONTAINER_DIAGRAM,
    DiagramType.COMPONENT_DIAGRAM,
    DiagramType.DYNAMIC_DIAGRAM,
    DiagramType.DEPLOYMENT_DIAGRAM,
)


class ContainerDiagram(Diagram):
    """
    Represents a [C4 Container diagram](https://c4model.com/diagrams/container).
    """

    type: ClassVar[DiagramType] = DiagramType.CONTAINER_DIAGRAM


class Container(Element):
    """
    Represents an application or service container in a C4 Container diagram.

    A container can be a web application, API, worker, or any executable unit
    of deployment. It may optionally include technology and shape hints.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        technology: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLContainerExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a container element.

        Args:
            label: Display name for the container. Required.
            description: Optional description of the container's purpose.
            technology: Optional technology stack used by the container.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the container. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            alias=alias,
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
        )

        self.technology = technology


class ContainerDb(ElementWithTechnology):
    """
    Represents a container specifically modeled as a database.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        technology: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLContainerStorageExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a database-like container element.

        Args:
            label: Display name for the container database. Required.
            description: Optional description text.
            technology: Optional technology stack used by the container.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the container database. If not
                provided, it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            technology=technology,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class ContainerQueue(ElementWithTechnology):
    """
    Represents a container modeled as a message queue or event broker.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        technology: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLContainerStorageExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a queue-like container element.

        Args:
            label: Display name for the container queue. Required.
            description: Optional description text.
            technology: Optional technology stack used by the container.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the container queue. If not provided,
                it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            technology=technology,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class ContainerExt(Container):
    """
    Represents an external container (outside the system boundary).
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES


class ContainerDbExt(ContainerDb):
    """
    Represents an external database container.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES


class ContainerQueueExt(ContainerQueue):
    """
    Represents an external message queue or broker.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES


class ContainerBoundary(Boundary):
    """
    Represents a boundary grouping containers within a system.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLBoundaryExtensions | None = None,
        mermaid: MermaidBoundaryExtensions | None = None,
        d2: D2BoundaryExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a container-level boundary.

        Args:
            label: Display name for the boundary. Required.
            description: Optional human-readable description of the boundary.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            mermaid: Mermaid-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the boundary. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            alias=alias,
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            mermaid=mermaid,
            d2=d2,
        )


__all__ = (
    "Container",
    "ContainerBoundary",
    "ContainerDb",
    "ContainerDbExt",
    "ContainerDiagram",
    "ContainerExt",
    "ContainerQueue",
    "ContainerQueueExt",
)
