from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from c4.diagrams.core import (
    Boundary,
    Diagram,
    DiagramType,
    ElementExtensions,
)
from c4.utils import MISSING, REQUIRED, Maybe, Required

if TYPE_CHECKING:  # pragma: no cover
    from c4.contrib.plantuml.extensions import (
        NodeExtensions as PlantUMLNodeExtensions,
    )

AllowedDiagramTypes = tuple[DiagramType, ...] | None


ALLOWED_DIAGRAM_TYPES: tuple[DiagramType, ...] = (
    DiagramType.DEPLOYMENT_DIAGRAM,
)


class DeploymentDiagram(Diagram):
    """
    Represents a [C4 Deployment Diagram](https://c4model.com/diagrams/deployment).

    A deployment diagram shows how software systems and containers are
    mapped onto infrastructure nodes, such as servers, devices,
    or cloud services.
    """

    type: ClassVar[DiagramType] = DiagramType.DEPLOYMENT_DIAGRAM


class Node(Boundary):
    """
    Represents a deployment node in the C4 model.

    A Node is a container for deployment elements and can optionally include
    a sprite for visual representation (e.g., server icon, cloud logo).

    Nodes can be nested, and manage their own child elements.
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLNodeExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a new Node element.

        Args:
            label: Display name for the node. Required.
            description: Optional description shown in the rendered diagram.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            alias: Unique identifier for the node. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            label=label,
            alias=alias,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
        )


class DeploymentNode(Node):
    """
    Represents a deployment-specific node in the C4 model.

    Used to group containers or systems that are deployed together on a
    specific machine or environment (e.g., EC2 instance, on-prem server).
    """

    allowed_diagram_types: AllowedDiagramTypes = ALLOWED_DIAGRAM_TYPES

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLNodeExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a deployment node element.

        Args:
            label: Display name for the deployment node. Required.
            description: Optional description shown in the rendered diagram.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            alias: Unique identifier for the deployment node. If not provided,
                it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            alias=alias,
        )


__all__ = (
    "DeploymentDiagram",
    "DeploymentNode",
    "Node",
)
