from __future__ import annotations

from typing import TYPE_CHECKING, ClassVar

from c4.diagrams.core import (
    Boundary,
    Diagram,
    DiagramType,
    Element,
    ElementExtensions,
)
from c4.utils import MISSING, REQUIRED, Maybe, Required

if TYPE_CHECKING:  # pragma: no cover
    from c4.contrib.d2.extensions import (
        BoundaryExtensions as D2BoundaryExtensions,
    )
    from c4.contrib.d2.extensions import (
        ElementExtensions as D2ElementExtensions,
    )
    from c4.contrib.mermaid.extensions import (
        BoundaryExtensions as MermaidBoundaryExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        BoundaryExtensions as PlantUMLBoundaryExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        PersonExtensions as PlantUMLPersonExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        SystemExtensions as PlantUMLSystemExtensions,
    )
    from c4.contrib.plantuml.extensions import (
        SystemStorageExtensions as PlantUMLSystemStorageExtensions,
    )


class SystemContextDiagram(Diagram):
    """
    Represents a [C4 System Context Diagram](https://c4model.com/diagrams/system-context).
    """

    type: ClassVar[DiagramType] = DiagramType.SYSTEM_CONTEXT_DIAGRAM


class SystemLandscapeDiagram(Diagram):
    """
    Represents a [C4 System Landscape Diagram](https://c4model.com/diagrams/system-landscape).
    """

    type: ClassVar[DiagramType] = DiagramType.SYSTEM_LANDSCAPE_DIAGRAM


class Person(Element):
    """
    Represents a person (actor) interacting with the system.
    """

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLPersonExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a person element.

        Args:
            label: Display name for the person. Required.
            description: Optional description text.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the person. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class PersonExt(Person):
    """
    Represents an external person (actor) interacting with the system.
    """


class System(Element):
    """
    Represents a software system in the C4 model.
    """

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLSystemExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a software system element.

        Args:
            label: Display name for the system. Required.
            description: Optional description for the system.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the system. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            alias=alias,
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
        )


class SystemDb(Element):
    """
    Represents a system database (storage-centric system) in the C4 model.
    """

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLSystemStorageExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a database-like system element.

        Args:
            label: Display name for the system database. Required.
            description: Optional description text.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the system database. If not provided,
                it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class SystemQueue(Element):
    """
    Represents a message queue or streaming system in the C4 model.
    """

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLSystemStorageExtensions | None = None,
        d2: D2ElementExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize a queue-like system element.

        Args:
            label: Display name for the system queue. Required.
            description: Optional description text.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the system queue. If not provided,
                it is autogenerated from the label.
        """
        super().__init__(
            label=label,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            d2=d2,
            alias=alias,
        )


class SystemExt(System):
    """
    Represents an external system interacting with the system under
    consideration.
    """


class SystemDbExt(SystemDb):
    """
    Represents an external system database.
    """


class SystemQueueExt(SystemQueue):
    """
    Represents an external system queue or messaging system.
    """


class EnterpriseBoundary(Boundary):
    """
    Represents an enterprise boundary in a system landscape or context diagram.

    Used to group systems and actors that belong to the same
    organizational unit.
    """

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLBoundaryExtensions | None = None,
        mermaid: MermaidBoundaryExtensions | None = None,
        d2: D2BoundaryExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize the enterprise boundary element.

        Args:
            label: Display name for the boundary. Required.
            description: Optional description.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            mermaid: Mermaid-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the boundary. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            label=label,
            alias=alias,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            mermaid=mermaid,
            d2=d2,
        )


class SystemBoundary(Boundary):
    """
    Represents the boundary around a specific system.

    Used to group containers or components that belong to a single system.
    """

    def __init__(
        self,
        label: Required[str] = REQUIRED,
        description: str | None = None,
        extensions: ElementExtensions | None = None,
        plantuml: PlantUMLBoundaryExtensions | None = None,
        mermaid: MermaidBoundaryExtensions | None = None,
        d2: D2BoundaryExtensions | None = None,
        alias: Maybe[str] = MISSING,
    ) -> None:
        """
        Initialize the system boundary element.

        Args:
            label: Display name for the boundary. Required.
            description: Optional description.
            extensions: Backend-specific extension data.
            plantuml: PlantUML-specific extension data.
            mermaid: Mermaid-specific extension data.
            d2: D2-specific extension data.
            alias: Unique identifier for the boundary. If not provided, it is
                autogenerated from the label.
        """
        super().__init__(
            label=label,
            alias=alias,
            description=description,
            extensions=extensions,
            plantuml=plantuml,
            mermaid=mermaid,
            d2=d2,
        )


__all__ = (
    "EnterpriseBoundary",
    "Person",
    "PersonExt",
    "System",
    "SystemBoundary",
    "SystemContextDiagram",
    "SystemDb",
    "SystemDbExt",
    "SystemExt",
    "SystemLandscapeDiagram",
    "SystemQueue",
    "SystemQueueExt",
)
