direction: right
aws: {
  label: "AWS"
  private_subnet: {
    label: "Private Subnet"
    worker: "Worker\n[Python]"
  }
  public_subnet: {
    label: "Public Subnet"
    web_app: "Web App\n[React]"
  }
  ec2: {
    label: "EC2"
    api: "API\n[FastAPI]"
  }
  blue_node: {
    label: "Blue Node"
    blue_api: "Blue API\n[FastAPI]"
  }
  green_node: {
    label: "Green Node"
    green_api: "Green API\n[FastAPI]"
  }
}
