direction: right
classes: {
  c4_person: {
    style.fill: "#f5f1ff"
    style.stroke: "#6f4bb2"
    style.font-color: "#211436"
  }
}
big_bank: {
  label: "Big Bank"
  customer: {
    label: "Customer"
    shape: c4-person
    class: ["c4_person"]
  }
  online_banking: {
    label: "Online Banking"
    banking_system: "Banking System"
  }
}
big_bank.customer -> big_bank.online_banking.banking_system: "Uses"
