direction: right
classes: {
  c4_database: {
    style.fill: "#edf7ff"
    style.stroke: "#2d6f9f"
  }
}
application: {
  label: "Application"
  web_app: "Web App\n[React]"
  backend: {
    label: "Backend"
    api: "API\n[Python]"
    database: {
      label: "Database\n[PostgreSQL]"
      shape: cylinder
      class: ["c4_database"]
    }
  }
}
