from __future__ import annotations

from typing import Any, ClassVar, Generic, cast

from pydantic import BaseModel, Field

from c4.converters.json.schemas.base import (
    BaseSchemaItem,
    JSONSchemaMixin,
    TDiagramElement,
    TypeDiagramElement,
)
from c4.converters.json.schemas.renderers.plantuml import (
    PlantUMLLayoutOptionsSchema,
)
from c4.diagrams.core import (
    DEFAULT_PROPERTIES_HEADER,
    BaseDiagramElement,
    Diagram,
    Layout,
    LayoutType,
    Relationship,
    RelationshipType,
)

TypeDiagram = type[Diagram]


_DEFAULT_PROPERTIES_HEADER_LIST = list(DEFAULT_PROPERTIES_HEADER)


class DiagramElementPropertiesSchema(BaseModel, JSONSchemaMixin):
    show_header: bool = Field(
        True,
        description="Whether to display the header row.",
    )
    header: list[str] = Field(
        description="Header columns.",
        min_length=1,
        default=_DEFAULT_PROPERTIES_HEADER_LIST,
    )
    properties: list[list[str]] = Field(
        ...,
        description="List of rows (each row is a list of string values).",
    )

    @property
    def is_default_header(self) -> bool:
        return self.header == _DEFAULT_PROPERTIES_HEADER_LIST


class PropertiesMixin:
    def _add_properties(
        self,
        element: BaseDiagramElement,
        properties: DiagramElementPropertiesSchema,
    ) -> None:
        if not properties.show_header:
            element.without_property_header()
        elif properties.header and not properties.is_default_header:
            element.set_property_header(*properties.header)

        for props in properties.properties:
            element.add_property(*props)


class WithType:
    type_: str | None = Field(
        None,
        description="Optional custom type/stereotype label.",
        alias="stereotype",
    )


class WithBaseShape:
    base_shape: str | None = Field(
        None,
        description=(
            "Optional base shape override (supported by some element classes)."
        ),
    )


class WithTechnology:
    technology: str | None = Field(
        None,
        description="Optional technology.",
    )


class ElementBase(BaseSchemaItem, PropertiesMixin, Generic[TDiagramElement]):
    type: str = Field(
        ..., description="Discriminator identifying the element type."
    )
    label: str = Field(
        min_length=1, description="Display name for the element."
    )
    description: str | None = Field(
        None, description="Optional description text."
    )
    sprite: str | None = Field(
        None, description="Optional sprite/icon reference."
    )
    tags: list[str] = Field(
        default_factory=list,
        description=(
            "Optional tags for grouping/styling. "
            "These tags can be referenced by `tag_stereo` in tag definitions."
        ),
    )
    link: str | None = Field(
        None, description="Optional URL associated with the element."
    )
    alias: str | None = Field(
        None,
        description=(
            "Unique identifier for the element. If not provided, "
            "it is autogenerated from the label."
        ),
    )
    properties: DiagramElementPropertiesSchema | None = Field(
        None, description="Optional property table metadata."
    )

    def to_diagram_element(self, **overrides: Any) -> BaseDiagramElement:
        """
        Instantiate the target diagram element using validated
        and filtered kwargs.
        """
        element = super().to_diagram_element(**overrides)

        if self.properties:
            self._add_properties(element, self.properties)

        return cast(BaseDiagramElement, element)


class RelationshipSchema(BaseSchemaItem[Relationship], PropertiesMixin):
    type: RelationshipType = Field(..., description="Type of the relationship.")
    from_: str = Field(
        ...,
        min_length=1,
        description="The source element alias (or unique label).",
        alias="from",
    )
    to: str = Field(
        ...,
        min_length=1,
        description="The destination element alias (or unique label).",
    )
    label: str = Field(description="The label shown on the relationship edge.")
    description: str | None = Field(
        None, description="Additional details about the relationship."
    )
    technology: str | None = Field(
        None,
        description="The technology used in the communication.",
    )
    sprite: str | None = Field(
        None, description="Optional sprite/icon to represent the relationship."
    )
    tags: list[str] = Field(
        default_factory=list,
        description=(
            "Optional tags for grouping/styling. "
            "These tags can be referenced by `tag_stereo` in tag definitions."
        ),
    )
    link: str | None = Field(
        None, description="Optional URL link associated with the relationship."
    )
    properties: DiagramElementPropertiesSchema | None = Field(
        None, description="Optional property table metadata."
    )

    def _get_diagram_element_class(self) -> TypeDiagramElement | None:
        return Relationship.get_relationship_by_type(self.type)

    def to_diagram_element(self, **overrides: Any) -> BaseDiagramElement:
        """
        Instantiate the target diagram element using validated
        and filtered kwargs.
        """
        element = super().to_diagram_element(**overrides)

        if self.properties:
            self._add_properties(element, self.properties)

        return cast(BaseDiagramElement, element)


class LayoutSchema(BaseSchemaItem[Layout]):
    type: LayoutType = Field(..., description="Type of the layout.")
    from_: str = Field(
        ...,
        min_length=1,
        description="The source element alias (or unique label).",
        alias="from",
    )
    to: str = Field(
        ...,
        min_length=1,
        description="The destination element alias (or unique label).",
    )

    def _get_diagram_element_class(self) -> TypeDiagramElement | None:
        return Layout.get_layout_by_type(self.type)


class RenderOptionsSchema(BaseSchemaItem):
    plantuml: PlantUMLLayoutOptionsSchema | None = Field(
        None, description="PlantUML-specific render options."
    )


class BaseDiagramSchema(BaseSchemaItem):
    type: str = Field(
        ...,
    )
    title: str | None = Field(None, description="Optional diagram title.")
    layouts: list[LayoutSchema] = Field(
        default_factory=list,
        description="Relative layout constraints between elements.",
    )

    render_options: RenderOptionsSchema | None = Field(
        None, description="Optional renderer-specific options"
    )

    __diagram_class__: ClassVar[TypeDiagram] = Diagram


class BoundaryBase(BaseSchemaItem, PropertiesMixin, Generic[TDiagramElement]):
    type: str = Field(
        ..., description="Discriminator identifying the element type."
    )
    label: str = Field(
        min_length=1, description="Display name for the element."
    )
    description: str | None = Field(
        None, description="Optional description text."
    )
    tags: list[str] = Field(
        default_factory=list,
        description=(
            "Optional tags for grouping/styling. "
            "These tags can be referenced by `tag_stereo` in tag definitions."
        ),
    )
    link: str | None = Field(
        None, description="Optional URL associated with the element."
    )
    alias: str | None = Field(
        None,
        description=(
            "Unique identifier for the element. If not provided, "
            "it is autogenerated from the label."
        ),
    )
    properties: DiagramElementPropertiesSchema | None = Field(
        None, description="Optional property table metadata."
    )

    def _to_diagram_element_kwargs(self) -> dict[str, Any]:
        kwargs = self.model_dump(
            mode="python",
            exclude={
                "elements",
                "boundaries",
                "relationships",
                "alias",
            },
        )
        for key, value in kwargs.items():
            value = value or None
            kwargs[key] = value

        # Keep alias only if provided (avoid injecting None).
        if self.alias:
            kwargs["alias"] = self.alias

        return kwargs


class WithBoundaryRelationship:
    relationships: list[RelationshipSchema] = Field(
        default_factory=list,
        description="Relationships declared inside the boundary.",
    )
