from __future__ import annotations

from typing import Any, ClassVar, Generic, Literal, cast

from pydantic import BaseModel, Field

from c4.converters.json.schemas.base import (
    BaseSchemaItem,
    JSONSchemaMixin,
    TDiagramElement,
    TypeDiagramElement,
)
from c4.diagrams.core import (
    DEFAULT_PROPERTIES_HEADER,
    BaseDiagramElement,
    Diagram,
    Relationship,
    RelationshipType,
)

TypeDiagram = type[Diagram]


_DEFAULT_PROPERTIES_HEADER_LIST = list(DEFAULT_PROPERTIES_HEADER)


class DiagramElementPropertiesSchema(JSONSchemaMixin, BaseModel):
    """JSON schema for tabular diagram element properties."""

    show_header: bool = Field(
        True,
        description="Whether to display the header row.",
    )
    header: list[str] = Field(
        description="Header columns.",
        min_length=1,
        default=_DEFAULT_PROPERTIES_HEADER_LIST,
    )
    properties: list[list[str]] = Field(
        ...,
        description="List of rows (each row is a list of string values).",
    )

    @property
    def is_default_header(self) -> bool:
        """Return whether the property table uses the default header."""
        return self.header == _DEFAULT_PROPERTIES_HEADER_LIST


class PropertiesMixin:
    """Mixin that applies property table metadata to diagram elements."""

    def _add_properties(
        self,
        element: BaseDiagramElement,
        properties: DiagramElementPropertiesSchema,
    ) -> None:
        """Apply schema property metadata to a diagram element."""
        if not properties.show_header:
            element.without_property_header()
        elif properties.header and not properties.is_default_header:
            element.set_property_header(*properties.header)

        for props in properties.properties:
            element.add_property(*props)


class WithTechnology:
    """Mixin for schema items that carry an optional technology label."""

    technology: str | None = Field(
        None,
        description="Optional technology.",
    )


class ElementBase(BaseSchemaItem, PropertiesMixin, Generic[TDiagramElement]):
    """Base JSON schema for C4 elements with labels, aliases, and properties."""

    type: str = Field(
        ..., description="Discriminator identifying the element type."
    )
    label: str = Field(
        min_length=1, description="Display name for the element."
    )
    description: str | None = Field(
        None, description="Optional description text."
    )
    alias: str | None = Field(
        None,
        description=(
            "Unique identifier for the element. If not provided, "
            "it is autogenerated from the label."
        ),
    )
    properties: DiagramElementPropertiesSchema | None = Field(
        None, description="Optional property table metadata."
    )

    def to_diagram_element(self, **overrides: Any) -> BaseDiagramElement:
        """
        Instantiate the target diagram element using validated
        and filtered kwargs.
        """
        element = super().to_diagram_element(**overrides)

        if self.properties:
            self._add_properties(element, self.properties)

        return cast(BaseDiagramElement, element)


class RelationshipSchema(BaseSchemaItem[Relationship], PropertiesMixin):
    """
    This schema describes the [`Relationship`][c4.diagrams.core.Relationship]
    diagram component.
    """

    type: Literal[RelationshipType.REL.value] = Field(  # type: ignore[name-defined]
        ..., description="Type of the relationship."
    )
    from_: str = Field(
        ...,
        min_length=1,
        description="The source element alias (or unique label).",
        alias="from",
    )
    to: str = Field(
        ...,
        min_length=1,
        description="The destination element alias (or unique label).",
    )
    label: str = Field(description="The label shown on the relationship edge.")
    description: str | None = Field(
        None, description="Additional details about the relationship."
    )
    technology: str | None = Field(
        None,
        description="The technology used in the communication.",
    )
    properties: DiagramElementPropertiesSchema | None = Field(
        None, description="Optional property table metadata."
    )

    def _get_diagram_element_class(self) -> TypeDiagramElement | None:
        """Return the core relationship element class for this schema."""
        return Relationship.get_relationship_by_type(
            RelationshipType(self.type)
        )

    def to_diagram_element(self, **overrides: Any) -> BaseDiagramElement:
        """
        Instantiate the target diagram element using validated
        and filtered kwargs.
        """
        element = super().to_diagram_element(**overrides)

        if self.properties:
            self._add_properties(element, self.properties)

        return cast(BaseDiagramElement, element)


class BaseDiagramSchema(BaseSchemaItem):
    """Base JSON schema for C4 diagrams."""

    type: str = Field(
        ...,
    )
    title: str | None = Field(None, description="Optional diagram title.")

    __diagram_class__: ClassVar[TypeDiagram] = Diagram

    def to_diagram(self) -> Diagram:
        """Instantiate the diagram represented by this schema."""
        return self.__diagram_class__(title=self.title)


class BoundaryBase(BaseSchemaItem, PropertiesMixin, Generic[TDiagramElement]):
    """Base JSON schema for C4 boundaries."""

    type: str = Field(
        ..., description="Discriminator identifying the element type."
    )
    label: str = Field(
        min_length=1, description="Display name for the element."
    )
    description: str | None = Field(
        None, description="Optional description text."
    )
    alias: str | None = Field(
        None,
        description=(
            "Unique identifier for the element. If not provided, "
            "it is autogenerated from the label."
        ),
    )
    properties: DiagramElementPropertiesSchema | None = Field(
        None, description="Optional property table metadata."
    )

    def _to_diagram_element_kwargs(self) -> dict[str, Any]:
        """Return constructor kwargs for the target boundary element."""
        kwargs = self.model_dump(
            mode="python",
            exclude={
                "elements",
                "boundaries",
                "relationships",
                "alias",
            },
        )
        for key, value in kwargs.items():
            value = value or None
            kwargs[key] = value

        # Keep alias only if provided (avoid injecting None).
        if self.alias:
            kwargs["alias"] = self.alias

        return kwargs


class WithBoundaryRelationship:
    """Mixin for boundary schemas that can contain relationships."""

    relationships: list[RelationshipSchema] = Field(
        default_factory=list,
        description="Relationships declared inside the boundary.",
    )
