from typing import Any

import pytest

from c4.contrib.plantuml.converters.json.render_options import (
    BoundaryStyleSchema,
    BoundaryTagSchema,
    ContainerBoundaryStyleSchema,
    ElementStyleSchema,
    ElementTagSchema,
    NodeTagSchema,
    PlantUMLRenderOptionsSchema,
    SetSketchStyleSchema,
    ShowFloatingLegendSchema,
    ShowLegendSchema,
    ShowPersonSpriteSchema,
)
from c4.contrib.plantuml.converters.json.schemas import PlantUMLNodeSchema
from c4.contrib.plantuml.extensions import (
    BoundaryExtensions,
    ComponentExtensions,
    ContainerExtensions,
    ElementExtensions,
    NodeExtensions,
    RelationshipExtensions,
)
from c4.renderers.plantuml.options import (
    BoundaryStyle,
    BoundaryTag,
    ContainerBoundaryStyle,
    DiagramLayout,
    ElementStyle,
    ElementTag,
    NodeTag,
    PlantUMLRenderOptions,
    SetSketchStyle,
    ShowFloatingLegend,
    ShowLegend,
    ShowPersonSprite,
)


def test_plantuml_extension_schemas_are_importable():
    assert RelationshipExtensions.__optional_keys__ == frozenset((
        "sprite",
        "tags",
        "link",
        "index",
    ))
    assert "base_shape" in ElementExtensions.__optional_keys__
    assert "base_shape" in ContainerExtensions.__optional_keys__
    assert "base_shape" in ComponentExtensions.__optional_keys__
    assert "type" in BoundaryExtensions.__optional_keys__
    assert "type" in NodeExtensions.__optional_keys__


def test_plantuml_node_schema__moves_fields_to_extensions():
    schema = PlantUMLNodeSchema(
        type="Node",
        label="Runtime",
        sprite="server",
        tags=["runtime"],
        link="https://example.com/runtime",
        stereotype="Runtime Node",
    )

    result = schema._to_diagram_element_kwargs()

    assert result["plantuml"] == {
        "link": "https://example.com/runtime",
        "sprite": "server",
        "tags": ["runtime"],
        "type": "Runtime Node",
    }


def test_plantuml_render_options_schema__to_render_options__empty():
    schema = PlantUMLRenderOptionsSchema()
    expected_result = PlantUMLRenderOptions()

    result = schema.to_render_options()

    assert result == expected_result


@pytest.mark.parametrize(
    ("field_name", "field_value"),
    [
        ("layout", DiagramLayout.LAYOUT_TOP_DOWN),
        ("layout_with_legend", True),
        ("layout_as_sketch", True),
        ("hide_stereotype", True),
        ("hide_person_sprite", True),
        ("show_person_portrait", True),
        ("show_person_outline", True),
        ("without_property_header", True),
        ("legend_title", "Main legend"),
    ],
)
def test_plantuml_render_options_schema__to_render_options__plain_fields(
    field_name: str,
    field_value: Any,
):
    schema = PlantUMLRenderOptionsSchema.model_construct(**{
        field_name: field_value
    })
    expected_result = PlantUMLRenderOptions(**{field_name: field_value})

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__nested_models():
    schema = PlantUMLRenderOptionsSchema(
        set_sketch_style=SetSketchStyleSchema(
            bg_color="#ffffff",
            font_color="#222222",
            warning_color="#ff9900",
            font_name="Fira Code",
            footer_warning="Draft",
            footer_text="Generated by tests",
        ),
        show_legend=ShowLegendSchema(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegendSchema(
            alias="legend_box",
            hide_stereotype=False,
            details="Small",
        ),
        show_person_sprite=ShowPersonSpriteSchema(alias="person_sprite"),
    )
    expected_result = PlantUMLRenderOptions(
        set_sketch_style=SetSketchStyle(
            bg_color="#ffffff",
            font_color="#222222",
            warning_color="#ff9900",
            font_name="Fira Code",
            footer_warning="Draft",
            footer_text="Generated by tests",
        ),
        show_legend=ShowLegend(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegend(
            alias="legend_box",
            hide_stereotype=False,
            details="Small",
        ),
        show_person_sprite=ShowPersonSprite(alias="person_sprite"),
    )

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__tags():
    schema = PlantUMLRenderOptionsSchema(
        tags=[
            ElementTagSchema(
                type="ElementTag",
                tag_stereo="critical",
                legend_text="Critical component",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ff0000",
                font_color="#ffffff",
                border_color="#990000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ]
    )
    expected_result = PlantUMLRenderOptions(
        tags=[
            ElementTag(
                tag_stereo="critical",
                legend_text="Critical component",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ff0000",
                font_color="#ffffff",
                border_color="#990000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ]
    )

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__boundary_and_node_tags():
    schema = PlantUMLRenderOptionsSchema(
        tags=[
            BoundaryTagSchema(
                type="BoundaryTag",
                tag_stereo="secure_zone",
                stereotype="System",
                legend_text="Secure zone",
                legend_sprite="img:zone",
                sprite="img:lock",
                bg_color="#f8fafc",
                font_color="#0f172a",
                border_color="#334155",
                shadowing=False,
                shape="RoundedBoxShape",
                border_style="DashedLine",
                border_thickness="2",
            ),
            NodeTagSchema(
                type="NodeTag",
                tag_stereo="runtime",
                stereotype="Kubernetes node",
            ),
        ]
    )
    expected_result = PlantUMLRenderOptions(
        tags=[
            BoundaryTag(
                tag_stereo="secure_zone",
                type_="System",
                legend_text="Secure zone",
                legend_sprite="img:zone",
                sprite="img:lock",
                bg_color="#f8fafc",
                font_color="#0f172a",
                border_color="#334155",
                shadowing=False,
                shape="RoundedBoxShape",
                border_style="DashedLine",
                border_thickness="2",
            ),
            NodeTag(
                tag_stereo="runtime",
                type_="Kubernetes node",
                shadowing=False,
            ),
        ]
    )

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__styles():
    schema = PlantUMLRenderOptionsSchema(
        styles=[
            ElementStyleSchema(
                type="ElementStyle",
                element_name="api",
                bg_color="#f5f5f5",
                font_color="#111111",
                border_color="#222222",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Public API",
                legend_sprite="img:legend_api",
                border_style="DashedLine",
                border_thickness="1",
            )
        ]
    )
    expected_result = PlantUMLRenderOptions(
        styles=[
            ElementStyle(
                element_name="api",
                bg_color="#f5f5f5",
                font_color="#111111",
                border_color="#222222",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Public API",
                legend_sprite="img:legend_api",
                border_style="DashedLine",
                border_thickness="1",
            )
        ]
    )

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__boundary_styles():
    schema = PlantUMLRenderOptionsSchema(
        styles=[
            BoundaryStyleSchema(
                type="BoundaryStyle",
                element_name="system",
                stereotype="System",
                sprite="img:system_boundary",
            ),
            ContainerBoundaryStyleSchema(
                type="ContainerBoundaryStyle",
                stereotype="Container",
                sprite="img:container_boundary",
            ),
        ]
    )
    expected_result = PlantUMLRenderOptions(
        styles=[
            BoundaryStyle(
                element_name="system",
                type_="System",
                sprite="img:system_boundary",
            ),
            ContainerBoundaryStyle(
                type_="Container",
                sprite="img:container_boundary",
            ),
        ]
    )

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__styles__empty():
    schema = PlantUMLRenderOptionsSchema(
        styles=[
            ElementStyleSchema(
                type="ElementStyle",
                element_name="api",
            )
        ]
    )
    expected_result = PlantUMLRenderOptions(
        styles=[
            ElementStyle(
                element_name="api",
                bg_color=None,
                font_color=None,
                border_color=None,
                shadowing=None,
                shape=None,
                sprite=None,
                technology=None,
                legend_text=None,
                legend_sprite=None,
                border_style=None,
                border_thickness=None,
            )
        ]
    )

    result = schema.to_render_options()

    assert result == expected_result


def test_plantuml_render_options_schema__to_render_options__complex():
    schema = PlantUMLRenderOptionsSchema(
        layout=DiagramLayout.LAYOUT_LEFT_RIGHT,
        layout_with_legend=True,
        layout_as_sketch=True,
        set_sketch_style=SetSketchStyleSchema(
            bg_color="#fcfcfc",
            font_color="#202020",
            footer_text="Internal use only",
        ),
        show_legend=ShowLegendSchema(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegendSchema(
            alias="floating_legend",
            hide_stereotype=True,
            details="Small",
        ),
        hide_stereotype=True,
        hide_person_sprite=True,
        show_person_sprite=ShowPersonSpriteSchema(alias="person_icon"),
        show_person_portrait=True,
        show_person_outline=True,
        without_property_header=True,
        legend_title="Architecture legend",
        tags=[
            ElementTagSchema(
                type="ElementTag",
                tag_stereo="critical",
                legend_text="Critical",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ffe5e5",
                font_color="#111111",
                border_color="#cc0000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
        styles=[
            ElementStyleSchema(
                type="ElementStyle",
                element_name="orders_api",
                bg_color="#eef6ff",
                font_color="#0f172a",
                border_color="#2563eb",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Orders API",
                legend_sprite="img:orders_api",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
    )
    expected_result = PlantUMLRenderOptions(
        layout=DiagramLayout.LAYOUT_LEFT_RIGHT,
        layout_with_legend=True,
        layout_as_sketch=True,
        set_sketch_style=SetSketchStyle(
            bg_color="#fcfcfc",
            font_color="#202020",
            footer_text="Internal use only",
        ),
        show_legend=ShowLegend(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegend(
            alias="floating_legend",
            hide_stereotype=True,
            details="Small",
        ),
        hide_stereotype=True,
        hide_person_sprite=True,
        show_person_sprite=ShowPersonSprite(alias="person_icon"),
        show_person_portrait=True,
        show_person_outline=True,
        without_property_header=True,
        legend_title="Architecture legend",
        tags=[
            ElementTag(
                tag_stereo="critical",
                legend_text="Critical",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ffe5e5",
                font_color="#111111",
                border_color="#cc0000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
        styles=[
            ElementStyle(
                element_name="orders_api",
                bg_color="#eef6ff",
                font_color="#0f172a",
                border_color="#2563eb",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Orders API",
                legend_sprite="img:orders_api",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
    )

    result = schema.to_render_options()

    assert result == expected_result
