from typing import Any

import pytest

from c4.converters.json.schemas.renderers.plantuml import (
    ElementStyleSchema,
    ElementTagSchema,
    PlantUMLLayoutOptionsSchema,
    SetSketchStyleSchema,
    ShowFloatingLegendSchema,
    ShowLegendSchema,
    ShowPersonSpriteSchema,
)
from c4.renderers.plantuml.layout_options import (
    DiagramLayout,
    ElementStyle,
    ElementTag,
    LayoutConfig,
    SetSketchStyle,
    ShowFloatingLegend,
    ShowLegend,
    ShowPersonSprite,
)


def test_plantuml_layout_options_schema__to_layout_config__empty():
    schema = PlantUMLLayoutOptionsSchema()
    expected_result = LayoutConfig()

    result = schema.to_layout_config()

    assert result == expected_result


@pytest.mark.parametrize(
    ("field_name", "field_value"),
    [
        ("layout", DiagramLayout.LAYOUT_TOP_DOWN),
        ("layout_with_legend", True),
        ("layout_as_sketch", True),
        ("hide_stereotype", True),
        ("hide_person_sprite", True),
        ("show_person_portrait", True),
        ("show_person_outline", True),
        ("without_property_header", True),
        ("legend_title", "Main legend"),
    ],
)
def test_plantuml_layout_options_schema__to_layout_config__plain_fields(
    field_name: str,
    field_value: Any,
):
    schema = PlantUMLLayoutOptionsSchema.model_construct(**{
        field_name: field_value
    })
    expected_result = LayoutConfig(**{field_name: field_value})

    result = schema.to_layout_config()

    assert result == expected_result


def test_plantuml_layout_options_schema__to_layout_config__nested_models():
    schema = PlantUMLLayoutOptionsSchema(
        set_sketch_style=SetSketchStyleSchema(
            bg_color="#ffffff",
            font_color="#222222",
            warning_color="#ff9900",
            font_name="Fira Code",
            footer_warning="Draft",
            footer_text="Generated by tests",
        ),
        show_legend=ShowLegendSchema(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegendSchema(
            alias="legend_box",
            hide_stereotype=False,
            details="Small",
        ),
        show_person_sprite=ShowPersonSpriteSchema(alias="person_sprite"),
    )
    expected_result = LayoutConfig(
        set_sketch_style=SetSketchStyle(
            bg_color="#ffffff",
            font_color="#222222",
            warning_color="#ff9900",
            font_name="Fira Code",
            footer_warning="Draft",
            footer_text="Generated by tests",
        ),
        show_legend=ShowLegend(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegend(
            alias="legend_box",
            hide_stereotype=False,
            details="Small",
        ),
        show_person_sprite=ShowPersonSprite(alias="person_sprite"),
    )

    result = schema.to_layout_config()

    assert result == expected_result


def test_plantuml_layout_options_schema__to_layout_config__tags():
    schema = PlantUMLLayoutOptionsSchema(
        tags=[
            ElementTagSchema(
                type="ElementTag",
                tag_stereo="critical",
                legend_text="Critical component",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ff0000",
                font_color="#ffffff",
                border_color="#990000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ]
    )
    expected_result = LayoutConfig(
        tags=[
            ElementTag(
                tag_stereo="critical",
                legend_text="Critical component",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ff0000",
                font_color="#ffffff",
                border_color="#990000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ]
    )

    result = schema.to_layout_config()

    assert result == expected_result


def test_plantuml_layout_options_schema__to_layout_config__styles():
    schema = PlantUMLLayoutOptionsSchema(
        styles=[
            ElementStyleSchema(
                type="ElementStyle",
                element_name="api",
                bg_color="#f5f5f5",
                font_color="#111111",
                border_color="#222222",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Public API",
                legend_sprite="img:legend_api",
                border_style="DashedLine",
                border_thickness="1",
            )
        ]
    )
    expected_result = LayoutConfig(
        styles=[
            ElementStyle(
                element_name="api",
                bg_color="#f5f5f5",
                font_color="#111111",
                border_color="#222222",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Public API",
                legend_sprite="img:legend_api",
                border_style="DashedLine",
                border_thickness="1",
            )
        ]
    )

    result = schema.to_layout_config()

    assert result == expected_result


def test_plantuml_layout_options_schema__to_layout_config__styles__empty():
    schema = PlantUMLLayoutOptionsSchema(
        styles=[
            ElementStyleSchema(
                type="ElementStyle",
                element_name="api",
            )
        ]
    )
    expected_result = LayoutConfig(
        styles=[
            ElementStyle(
                element_name="api",
                bg_color="",
                font_color="",
                border_color="",
                shadowing="",
                shape="",
                sprite="",
                technology="",
                legend_text="",
                legend_sprite="",
                border_style="",
                border_thickness="",
            )
        ]
    )

    result = schema.to_layout_config()

    assert result == expected_result


def test_plantuml_layout_options_schema__to_layout_config__complex():
    schema = PlantUMLLayoutOptionsSchema(
        layout=DiagramLayout.LAYOUT_LEFT_RIGHT,
        layout_with_legend=True,
        layout_as_sketch=True,
        set_sketch_style=SetSketchStyleSchema(
            bg_color="#fcfcfc",
            font_color="#202020",
            footer_text="Internal use only",
        ),
        show_legend=ShowLegendSchema(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegendSchema(
            alias="floating_legend",
            hide_stereotype=True,
            details="Small",
        ),
        hide_stereotype=True,
        hide_person_sprite=True,
        show_person_sprite=ShowPersonSpriteSchema(alias="person_icon"),
        show_person_portrait=True,
        show_person_outline=True,
        without_property_header=True,
        legend_title="Architecture legend",
        tags=[
            ElementTagSchema(
                type="ElementTag",
                tag_stereo="critical",
                legend_text="Critical",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ffe5e5",
                font_color="#111111",
                border_color="#cc0000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
        styles=[
            ElementStyleSchema(
                type="ElementStyle",
                element_name="orders_api",
                bg_color="#eef6ff",
                font_color="#0f172a",
                border_color="#2563eb",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Orders API",
                legend_sprite="img:orders_api",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
    )
    expected_result = LayoutConfig(
        layout=DiagramLayout.LAYOUT_LEFT_RIGHT,
        layout_with_legend=True,
        layout_as_sketch=True,
        set_sketch_style=SetSketchStyle(
            bg_color="#fcfcfc",
            font_color="#202020",
            footer_text="Internal use only",
        ),
        show_legend=ShowLegend(
            hide_stereotype=False,
            details="Normal",
        ),
        show_floating_legend=ShowFloatingLegend(
            alias="floating_legend",
            hide_stereotype=True,
            details="Small",
        ),
        hide_stereotype=True,
        hide_person_sprite=True,
        show_person_sprite=ShowPersonSprite(alias="person_icon"),
        show_person_portrait=True,
        show_person_outline=True,
        without_property_header=True,
        legend_title="Architecture legend",
        tags=[
            ElementTag(
                tag_stereo="critical",
                legend_text="Critical",
                legend_sprite="img:critical",
                sprite="img:service",
                bg_color="#ffe5e5",
                font_color="#111111",
                border_color="#cc0000",
                shadowing=False,
                shape="RoundedBoxShape",
                technology="Python",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
        styles=[
            ElementStyle(
                element_name="orders_api",
                bg_color="#eef6ff",
                font_color="#0f172a",
                border_color="#2563eb",
                shadowing=False,
                shape="RoundedBoxShape",
                sprite="img:api",
                technology="FastAPI",
                legend_text="Orders API",
                legend_sprite="img:orders_api",
                border_style="SolidLine",
                border_thickness="2",
            )
        ],
    )

    result = schema.to_layout_config()

    assert result == expected_result
