C4Container
title Container diagram for Internet Banking System

System_Ext(email_system, "E-Mail System", "The internal Microsoft Exchange system")

Person(customer, "Customer", "A customer of the bank, with personal bank accounts")

System_Ext(banking_system, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Container_Boundary(c1, "Internet Banking") {
    Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to customers via their web browser")
    Container_Ext(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
    Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA")
    ContainerDb(database, "Database", "SQL Database", "Stores user registration information, hashed auth credentials, access logs, etc.")
    ContainerDb_Ext(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API")
}

Rel(customer, web_app, "Uses", "HTTPS")

Rel(customer, spa, "Uses", "HTTPS")

Rel(customer, mobile_app, "Uses")

Rel(web_app, spa, "Delivers")

Rel(spa, backend_api, "Uses", "async, JSON/HTTPS")

Rel(mobile_app, backend_api, "Uses", "async, JSON/HTTPS")

Rel_Back(database, backend_api, "Reads from and writes to", "sync, JDBC")

Rel(email_system, customer, "Sends e-mails to")

Rel(backend_api, email_system, "Sends e-mails using", "sync, SMTP")

Rel(backend_api, banking_system, "Uses", "sync/async, XML/HTTPS")

UpdateRelStyle(customer, web_app, $offsetX="90", $offsetY="60")
UpdateRelStyle(customer, spa, $offsetY="-40")
UpdateRelStyle(customer, mobile_app, $offsetY="-30")
UpdateRelStyle(web_app, spa, $offsetX="130")
UpdateRelStyle(email_system, customer, $offsetX="-45")
UpdateRelStyle(backend_api, email_system, $offsetX="-130", $offsetY="-60")
UpdateRelStyle(backend_api, banking_system, $offsetX="-140", $offsetY="-50")
