@startuml
' convert it with additional command line argument -DRELATIVE_INCLUDE="relative/absolute" to use locally
!if %variable_exists("RELATIVE_INCLUDE")
    !include %get_variable_value("RELATIVE_INCLUDE")/C4_Dynamic.puml
!else
    !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml
!endif

title Login Flow

Person(user, "User", "Signs in to the application.", $tags="")

System(web_app, "Web App", "Main application used by customers.", $tags="")

System_Ext(idp, "Identity Provider", "External authentication service.", $tags="")

Rel(user, web_app, "Opens sign-in page", "HTTPS", $tags="")
Rel(web_app, idp, "Authenticates user", "OIDC", $tags="")
Rel(idp, web_app, "Returns identity token", "OIDC", $tags="")

@enduml
